-- DROP TABLE IF EXISTS users CASCADE;

-- CREATE TABLE users (
--   id SERIAL PRIMARY KEY NOT NULL,
--   name VARCHAR(255) NOT NULL,
--   email VARCHAR(255) NOT NULL,
--   password VARCHAR(255) NOT NULL
-- );

DROP TABLE IF EXISTS photos CASCADE;

CREATE TABLE photos (
  id SERIAL PRIMARY KEY NOT NULL,
  description VARCHAR(5000) NOT NULL,
  url VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS paintings CASCADE;

CREATE TABLE paintings (
  id SERIAL PRIMARY KEY NOT NULL,
  description VARCHAR(5000) NOT NULL,
  url VARCHAR(255) NOT NULL,
  year INTEGER,
  materials VARCHAR(500) NOT NULL,
  price INTEGER
);

DROP TABLE IF EXISTS faqs CASCADE;

CREATE TABLE faqs (
  id SERIAL PRIMARY KEY NOT NULL,
  question VARCHAR(5000) NOT NULL,
  answer VARCHAR(5000) NOT NULL
);

DROP TABLE IF EXISTS messages CASCADE;

CREATE TABLE messages (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  message VARCHAR(255) NOT NULL
);
