-- INSERT INTO users (name, email, password) VALUES ('Super Mario', 'mario@nintendo.com', 'test');
-- INSERT INTO users (name, email, password) VALUES ('Luigi', 'luigi@nintendo.com', 'test');
-- INSERT INTO users (name, email, password) VALUES ('Peach', 'peach@nintendo.com', 'test');

INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/1-min.jpg');
INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/2-min.jpg');
INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/3-min.jpg');
INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/4-min.jpg');
INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/5-min.jpg');
INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/6-min.jpg');
INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/7-min.jpg');
INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/8-min.jpg');
INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/9-min.jpg');
INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/10-min.jpg');
INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/11-min.jpg');
INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/12-min.jpg');
INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/13-min.jpg');
INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/14-min.jpg');
INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/15-min.jpg');
INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/16-min.jpg');
INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/17-min.jpg');
INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/18-min.jpg');
INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/19-min.jpg');
INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/20-min.jpg');



INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '/adrianna-geo-1rBg5YSi00c-unsplash.jpg', 2019, 'oil, canvas, magic', 399);
INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '/birmingham-museums-trust-JZdPBgU6Nik-unsplash.jpg', 2019, 'oil, canvas, magic', 399);
INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '/bruce-warrington-oGSCKjhcJ9o-unsplash.jpg', 2019, 'oil, canvas, magic', 399);
INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '/europeana-qi9jveT9X6A-unsplash.jpg', 2019, 'oil, canvas, magic', 399);
INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '/europeana-VsnDYMWollM-unsplash.jpg', 2019, 'oil, canvas, magic', 399);
INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '/europeana-YIfFVwDcgu8-unsplash.jpg', 2019, 'oil, canvas, magic', 399);
INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '/europeana-YOzBc4aQsH0-unsplash.jpg', 2019, 'oil, canvas, magic', 399);
INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '/falco-negenman-kdNs6NZMaD4-unsplash.jpg', 2019, 'oil, canvas, magic', 399);
INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '/mcgill-library-eMw-fVXNpME-unsplash.jpg', 2019, 'oil, canvas, magic', 399);
INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '/sergio-souza-gOzD9CZTwXw-unsplash.jpg', 2019, 'oil, canvas, magic', 399);


INSERT INTO faqs (question, answer) VALUES ('Messenger bag cloud bread etsy post-ironic edison bulb?', 'Ethical cloud bread celiac, succulents actually bitters etsy mumblecore chia vinyl raw denim kogi forage. Franzen scenester mustache church-key synth. Unicorn everyday carry seitan cloud bread. Pok pok succulents humblebrag mixtape knausgaard. Tilde bitters everyday carry pug echo park fixie umami vexillologist squid bicycle rights biodiesel.');
INSERT INTO faqs (question, answer) VALUES ('Messenger bag cloud bread etsy post-ironic edison bulb?', 'Ethical cloud bread celiac, succulents actually bitters etsy mumblecore chia vinyl raw denim kogi forage. Franzen scenester mustache church-key synth. Unicorn everyday carry seitan cloud bread. Pok pok succulents humblebrag mixtape knausgaard. Tilde bitters everyday carry pug echo park fixie umami vexillologist squid bicycle rights biodiesel.');
INSERT INTO faqs (question, answer) VALUES ('Messenger bag cloud bread etsy post-ironic edison bulb?', 'Ethical cloud bread celiac, succulents actually bitters etsy mumblecore chia vinyl raw denim kogi forage. Franzen scenester mustache church-key synth. Unicorn everyday carry seitan cloud bread. Pok pok succulents humblebrag mixtape knausgaard. Tilde bitters everyday carry pug echo park fixie umami vexillologist squid bicycle rights biodiesel.');
INSERT INTO faqs (question, answer) VALUES ('Messenger bag cloud bread etsy post-ironic edison bulb?', 'Ethical cloud bread celiac, succulents actually bitters etsy mumblecore chia vinyl raw denim kogi forage. Franzen scenester mustache church-key synth. Unicorn everyday carry seitan cloud bread. Pok pok succulents humblebrag mixtape knausgaard. Tilde bitters everyday carry pug echo park fixie umami vexillologist squid bicycle rights biodiesel.');
INSERT INTO faqs (question, answer) VALUES ('Messenger bag cloud bread etsy post-ironic edison bulb?', 'Ethical cloud bread celiac, succulents actually bitters etsy mumblecore chia vinyl raw denim kogi forage. Franzen scenester mustache church-key synth. Unicorn everyday carry seitan cloud bread. Pok pok succulents humblebrag mixtape knausgaard. Tilde bitters everyday carry pug echo park fixie umami vexillologist squid bicycle rights biodiesel.');
INSERT INTO faqs (question, answer) VALUES ('Messenger bag cloud bread etsy post-ironic edison bulb?', 'Ethical cloud bread celiac, succulents actually bitters etsy mumblecore chia vinyl raw denim kogi forage. Franzen scenester mustache church-key synth. Unicorn everyday carry seitan cloud bread. Pok pok succulents humblebrag mixtape knausgaard. Tilde bitters everyday carry pug echo park fixie umami vexillologist squid bicycle rights biodiesel.');
INSERT INTO faqs (question, answer) VALUES ('Messenger bag cloud bread etsy post-ironic edison bulb?', 'Ethical cloud bread celiac, succulents actually bitters etsy mumblecore chia vinyl raw denim kogi forage. Franzen scenester mustache church-key synth. Unicorn everyday carry seitan cloud bread. Pok pok succulents humblebrag mixtape knausgaard. Tilde bitters everyday carry pug echo park fixie umami vexillologist squid bicycle rights biodiesel.');
INSERT INTO faqs (question, answer) VALUES ('Messenger bag cloud bread etsy post-ironic edison bulb?', 'Ethical cloud bread celiac, succulents actually bitters etsy mumblecore chia vinyl raw denim kogi forage. Franzen scenester mustache church-key synth. Unicorn everyday carry seitan cloud bread. Pok pok succulents humblebrag mixtape knausgaard. Tilde bitters everyday carry pug echo park fixie umami vexillologist squid bicycle rights biodiesel.');
