INSERT INTO users (name, email, password) VALUES ('Super Mario', 'mario@nintendo.com', 'test');
INSERT INTO users (name, email, password) VALUES ('Luigi', 'luigi@nintendo.com', 'test');
INSERT INTO users (name, email, password) VALUES ('Peach', 'peach@nintendo.com', 'test');

INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '../assets/photos/brooke-cagle-kElEigko7PU-unsplash.jpg');
INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '../assets/photos/engin-akyurt-Bgz6WeuuAgs-unsplash.jpg');
INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '../assets/photos/flaunter-WcXxxQYp_aM-unsplash.jpg');
INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '../assets/photos/jonathan-borba-XsY9xjQlPfw-unsplash.jpg');
INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '../assets/photos/mike-von-TPUGbQmyVwE-unsplash.jpg');
INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '../assets/photos/nikolay-hristov-Ky5RFFvvF4g-unsplash.jpg');
INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '../assets/photos/priscilla-du-preez-dlxLGIy-2VU-unsplash.jpg');
INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '../assets/photos/raphael-lovaski-Z8vVlWoOiSI-unsplash.jpg');
INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '..assets/photos/tamara-bellis-68csPWTnafo-unsplash.jpg');
INSERT INTO photos (description, url) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '../assets/photos/vino-li-vM39hbfERUk-unsplash.jpg');


INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '../assets/paintings/adrianna-geo-1rBg5YSi00c-unsplash.jpg', 2019, 'oil, canvas, magic', 399);
INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '../assets/paintings/birmingham-museums-trust-JZdPBgU6Nik-unsplash.jpg', 2019, 'oil, canvas, magic', 399);
INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '../assets/paintings/bruce-warrington-oGSCKjhcJ9o-unsplash.jpg', 2019, 'oil, canvas, magic', 399);
INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '../assets/paintings/europeana-qi9jveT9X6A-unsplash.jpg', 2019, 'oil, canvas, magic', 399);
INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '../assets/paintings/europeana-VsnDYMWollM-unsplash.jpg', 2019, 'oil, canvas, magic', 399);
INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '../assets/paintings/europeana-YIfFVwDcgu8-unsplash.jpg', 2019, 'oil, canvas, magic', 399);
INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '../assets/paintings/europeana-YOzBc4aQsH0-unsplash.jpg', 2019, 'oil, canvas, magic', 399);
INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '../assets/paintings/falco-negenman-kdNs6NZMaD4-unsplash.jpg', 2019, 'oil, canvas, magic', 399);
INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '../assets/paintings/mcgill-library-eMw-fVXNpME-unsplash.jpg', 2019, 'oil, canvas, magic', 399);
INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '../assets/paintings/sergio-souza-gOzD9CZTwXw-unsplash.jpg', 2019, 'oil, canvas, magic', 399);


INSERT INTO faqs (question, answer) VALUES ('Messenger bag cloud bread etsy post-ironic edison bulb?', 'Ethical cloud bread celiac, succulents actually bitters etsy mumblecore chia vinyl raw denim kogi forage. Franzen scenester mustache church-key synth. Unicorn everyday carry seitan cloud bread. Pok pok succulents humblebrag mixtape knausgaard. Tilde bitters everyday carry pug echo park fixie umami vexillologist squid bicycle rights biodiesel.');
INSERT INTO faqs (question, answer) VALUES ('Messenger bag cloud bread etsy post-ironic edison bulb?', 'Ethical cloud bread celiac, succulents actually bitters etsy mumblecore chia vinyl raw denim kogi forage. Franzen scenester mustache church-key synth. Unicorn everyday carry seitan cloud bread. Pok pok succulents humblebrag mixtape knausgaard. Tilde bitters everyday carry pug echo park fixie umami vexillologist squid bicycle rights biodiesel.');
INSERT INTO faqs (question, answer) VALUES ('Messenger bag cloud bread etsy post-ironic edison bulb?', 'Ethical cloud bread celiac, succulents actually bitters etsy mumblecore chia vinyl raw denim kogi forage. Franzen scenester mustache church-key synth. Unicorn everyday carry seitan cloud bread. Pok pok succulents humblebrag mixtape knausgaard. Tilde bitters everyday carry pug echo park fixie umami vexillologist squid bicycle rights biodiesel.');
INSERT INTO faqs (question, answer) VALUES ('Messenger bag cloud bread etsy post-ironic edison bulb?', 'Ethical cloud bread celiac, succulents actually bitters etsy mumblecore chia vinyl raw denim kogi forage. Franzen scenester mustache church-key synth. Unicorn everyday carry seitan cloud bread. Pok pok succulents humblebrag mixtape knausgaard. Tilde bitters everyday carry pug echo park fixie umami vexillologist squid bicycle rights biodiesel.');
INSERT INTO faqs (question, answer) VALUES ('Messenger bag cloud bread etsy post-ironic edison bulb?', 'Ethical cloud bread celiac, succulents actually bitters etsy mumblecore chia vinyl raw denim kogi forage. Franzen scenester mustache church-key synth. Unicorn everyday carry seitan cloud bread. Pok pok succulents humblebrag mixtape knausgaard. Tilde bitters everyday carry pug echo park fixie umami vexillologist squid bicycle rights biodiesel.');
INSERT INTO faqs (question, answer) VALUES ('Messenger bag cloud bread etsy post-ironic edison bulb?', 'Ethical cloud bread celiac, succulents actually bitters etsy mumblecore chia vinyl raw denim kogi forage. Franzen scenester mustache church-key synth. Unicorn everyday carry seitan cloud bread. Pok pok succulents humblebrag mixtape knausgaard. Tilde bitters everyday carry pug echo park fixie umami vexillologist squid bicycle rights biodiesel.');
INSERT INTO faqs (question, answer) VALUES ('Messenger bag cloud bread etsy post-ironic edison bulb?', 'Ethical cloud bread celiac, succulents actually bitters etsy mumblecore chia vinyl raw denim kogi forage. Franzen scenester mustache church-key synth. Unicorn everyday carry seitan cloud bread. Pok pok succulents humblebrag mixtape knausgaard. Tilde bitters everyday carry pug echo park fixie umami vexillologist squid bicycle rights biodiesel.');
INSERT INTO faqs (question, answer) VALUES ('Messenger bag cloud bread etsy post-ironic edison bulb?', 'Ethical cloud bread celiac, succulents actually bitters etsy mumblecore chia vinyl raw denim kogi forage. Franzen scenester mustache church-key synth. Unicorn everyday carry seitan cloud bread. Pok pok succulents humblebrag mixtape knausgaard. Tilde bitters everyday carry pug echo park fixie umami vexillologist squid bicycle rights biodiesel.');
