INSERT INTO collections (name, description, coverurl) VALUES ('Kink', 'Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/13-min.jpg');
INSERT INTO collections (name, description, coverurl) VALUES ('Portrait', 'Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/15-min.jpg');
INSERT INTO collections (name, description, coverurl) VALUES ('Photoschool', 'Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/1-min.jpg');
INSERT INTO collections (name, description, coverurl) VALUES ('Random', 'Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/16-min.jpg');

INSERT INTO stories (name, description, coverurl) VALUES ('Story 1 Name', 'Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/6-min.jpg');
INSERT INTO stories (name, description, coverurl) VALUES ('Story 2 Name', 'Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/17-min.jpg');
INSERT INTO stories (name, description, coverurl) VALUES ('Story 3 Name', 'Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/19-min.jpg');
INSERT INTO stories (name, description, coverurl) VALUES ('Story 4 Name', 'Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/20-min.jpg');

INSERT INTO photos (description, url, collection_id, story_id) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/1-min.jpg', 1, 3);
INSERT INTO photos (description, url, collection_id, story_id) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/2-min.jpg', 1, 3);
INSERT INTO photos (description, url, collection_id, story_id) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/3-min.jpg', 1, 2);
INSERT INTO photos (description, url, collection_id, story_id) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/4-min.jpg', 1, 2);
INSERT INTO photos (description, url, collection_id, story_id) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/5-min.jpg', 1, 1);
INSERT INTO photos (description, url, collection_id, story_id) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/6-min.jpg', 1, 1);
INSERT INTO photos (description, url, collection_id, story_id) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/7-min.jpg', 1, 1);
INSERT INTO photos (description, url, collection_id, story_id) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/8-min.jpg', 1, 4);
INSERT INTO photos (description, url, collection_id, story_id) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/9-min.jpg', 1, 4);
INSERT INTO photos (description, url, collection_id, story_id) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/10-min.jpg', 1, 3);
INSERT INTO photos (description, url, collection_id, story_id) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/11-min.jpg', 1, 4);
INSERT INTO photos (description, url, collection_id, story_id) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/12-min.jpg', 1, 4);
INSERT INTO photos (description, url, collection_id, story_id) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/13-min.jpg', 1, 4);
INSERT INTO photos (description, url, collection_id, story_id) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/14-min.jpg', 1, 4);
INSERT INTO photos (description, url, collection_id, story_id) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/15-min.jpg', 2, 1);
INSERT INTO photos (description, url, collection_id, story_id) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/16-min.jpg', 2, 1);
INSERT INTO photos (description, url, collection_id, story_id) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/18-min.jpg', 2, 1);
INSERT INTO photos (description, url, collection_id, story_id) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/19-min.jpg', 3, 3);
INSERT INTO photos (description, url, collection_id, story_id) VALUES ('Baby dIY blog slow-carb activated charcoal iPhone kickstarter church-key locavore normcore poke banjo palo santo subway tile. Bushwick tousled asymmetrical green juice. Iceland seitan paleo, viral tofu hammock humblebrag banjo tbh. Live-edge tbh meh hashtag kickstarter.', '/20-min.jpg', 4, 2);

INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '/adrianna-geo-1rBg5YSi00c-unsplash-min.jpg', 2019, 'oil, canvas, magic', 399);
INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '/birmingham-museums-trust-JZdPBgU6Nik-unsplash-min.jpg', 2019, 'oil, canvas, magic', 399);
INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '/bruce-warrington-oGSCKjhcJ9o-unsplash-min.jpg', 2019, 'oil, canvas, magic', 399);
INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '/europeana-qi9jveT9X6A-unsplash-min.jpg', 2019, 'oil, canvas, magic', 399);
INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '/europeana-VsnDYMWollM-unsplash-min.jpg', 2019, 'oil, canvas, magic', 399);
INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '/europeana-YIfFVwDcgu8-unsplash-min.jpg', 2019, 'oil, canvas, magic', 399);
INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '/europeana-YOzBc4aQsH0-unsplash-min.jpg', 2019, 'oil, canvas, magic', 399);
INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '/falco-negenman-kdNs6NZMaD4-unsplash-min.jpg', 2019, 'oil, canvas, magic', 399);
INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '/mcgill-library-eMw-fVXNpME-unsplash-min.jpg', 2019, 'oil, canvas, magic', 399);
INSERT INTO paintings (description, url, year, materials, price) VALUES ('Meditation glossier 8-bit snackwave mumblecore YOLO marfa pour-over pork belly XOXO photo booth. VHS put a bird on it mustache af, jean shorts selfies butcher meh ugh freegan. Cronut hell of organic live-edge iPhone kogi skateboard. Paleo master cleanse tilde vinyl. Cliche cronut tote bag readymade vice.', '/sergio-souza-gOzD9CZTwXw-unsplash-min.jpg', 2019, 'oil, canvas, magic', 399);

INSERT INTO faqs (question, answer) VALUES ('Messenger bag cloud bread etsy post-ironic edison bulb?', 'Ethical cloud bread celiac, succulents actually bitters etsy mumblecore chia vinyl raw denim kogi forage. Franzen scenester mustache church-key synth. Unicorn everyday carry seitan cloud bread. Pok pok succulents humblebrag mixtape knausgaard. Tilde bitters everyday carry pug echo park fixie umami vexillologist squid bicycle rights biodiesel.');
INSERT INTO faqs (question, answer) VALUES ('Messenger bag cloud bread etsy post-ironic edison bulb?', 'Ethical cloud bread celiac, succulents actually bitters etsy mumblecore chia vinyl raw denim kogi forage. Franzen scenester mustache church-key synth. Unicorn everyday carry seitan cloud bread. Pok pok succulents humblebrag mixtape knausgaard. Tilde bitters everyday carry pug echo park fixie umami vexillologist squid bicycle rights biodiesel.');
INSERT INTO faqs (question, answer) VALUES ('Messenger bag cloud bread etsy post-ironic edison bulb?', 'Ethical cloud bread celiac, succulents actually bitters etsy mumblecore chia vinyl raw denim kogi forage. Franzen scenester mustache church-key synth. Unicorn everyday carry seitan cloud bread. Pok pok succulents humblebrag mixtape knausgaard. Tilde bitters everyday carry pug echo park fixie umami vexillologist squid bicycle rights biodiesel.');
INSERT INTO faqs (question, answer) VALUES ('Messenger bag cloud bread etsy post-ironic edison bulb?', 'Ethical cloud bread celiac, succulents actually bitters etsy mumblecore chia vinyl raw denim kogi forage. Franzen scenester mustache church-key synth. Unicorn everyday carry seitan cloud bread. Pok pok succulents humblebrag mixtape knausgaard. Tilde bitters everyday carry pug echo park fixie umami vexillologist squid bicycle rights biodiesel.');
INSERT INTO faqs (question, answer) VALUES ('Messenger bag cloud bread etsy post-ironic edison bulb?', 'Ethical cloud bread celiac, succulents actually bitters etsy mumblecore chia vinyl raw denim kogi forage. Franzen scenester mustache church-key synth. Unicorn everyday carry seitan cloud bread. Pok pok succulents humblebrag mixtape knausgaard. Tilde bitters everyday carry pug echo park fixie umami vexillologist squid bicycle rights biodiesel.');
INSERT INTO faqs (question, answer) VALUES ('Messenger bag cloud bread etsy post-ironic edison bulb?', 'Ethical cloud bread celiac, succulents actually bitters etsy mumblecore chia vinyl raw denim kogi forage. Franzen scenester mustache church-key synth. Unicorn everyday carry seitan cloud bread. Pok pok succulents humblebrag mixtape knausgaard. Tilde bitters everyday carry pug echo park fixie umami vexillologist squid bicycle rights biodiesel.');

INSERT INTO blogEntries (title, slug, article, coverUrl, photoUrls, dateString) 
VALUES ('Post Title 1', 'post-title-1', 'Ethical cloud bread celiac, succulents actually bitters etsy mumblecore chia vinyl raw denim kogi forage. Franzen scenester mustache church-key synth. Unicorn everyday carry seitan cloud bread. Pok pok succulents humblebrag mixtape knausgaard. Tilde bitters everyday carry pug echo park fixie umami vexillologist squid bicycle rights biodiesel.'||chr(10)||'Im baby photo booth heirloom thundercats kitsch organic direct trade af ethical franzen health goth man braid dreamcatcher tumblr vape. Authentic messenger bag XOXO, pabst iPhone disrupt gochujang occupy venmo crucifix narwhal keytar edison bulb. Subway tile tumblr shaman, tattooed hot chicken tilde 90s gochujang fam gluten-free. Hammock succulents pour-over chillwave meggings chia.'||chr(10)||'Im baby photo booth heirloom thundercats kitsch organic direct trade af ethical franzen health goth man braid dreamcatcher tumblr vape. Authentic messenger bag XOXO, pabst iPhone disrupt gochujang occupy venmo crucifix narwhal keytar edison bulb. Subway tile tumblr shaman, tattooed hot chicken tilde 90s gochujang fam gluten-free. Hammock succulents pour-over chillwave meggings chia.', 
'/paintings/bruce-warrington-oGSCKjhcJ9o-unsplash-min.jpg',  ARRAY['/paintings/europeana-VsnDYMWollM-unsplash-min.jpg', '/paintings/mcgill-library-eMw-fVXNpME-unsplash-min.jpg', '/photos/5-min.jpg', '/photos/6-min.jpg'], 'April 6, 2021');
INSERT INTO blogEntries (title, slug, article, coverUrl, photoUrls, dateString) 
VALUES ('Post Title 2', 'post-title-2', 'Ethical cloud bread celiac, succulents actually bitters etsy mumblecore chia vinyl raw denim kogi forage. Franzen scenester mustache church-key synth. Unicorn everyday carry seitan cloud bread. Pok pok succulents humblebrag mixtape knausgaard. Tilde bitters everyday carry pug echo park fixie umami vexillologist squid bicycle rights biodiesel.'||chr(10)||'Im baby photo booth heirloom thundercats kitsch organic direct trade af ethical franzen health goth man braid dreamcatcher tumblr vape. Authentic messenger bag XOXO, pabst iPhone disrupt gochujang occupy venmo crucifix narwhal keytar edison bulb. Subway tile tumblr shaman, tattooed hot chicken tilde 90s gochujang fam gluten-free. Hammock succulents pour-over chillwave meggings chia.'||chr(10)||'Im baby photo booth heirloom thundercats kitsch organic direct trade af ethical franzen health goth man braid dreamcatcher tumblr vape. Authentic messenger bag XOXO, pabst iPhone disrupt gochujang occupy venmo crucifix narwhal keytar edison bulb. Subway tile tumblr shaman, tattooed hot chicken tilde 90s gochujang fam gluten-free. Hammock succulents pour-over chillwave meggings chia.', 
'/paintings/europeana-qi9jveT9X6A-unsplash-min.jpg',  ARRAY['/paintings/europeana-YOzBc4aQsH0-unsplash-min.jpg', '/paintings/europeana-VsnDYMWollM-unsplash-min.jpg', '/photos/19-min.jpg', '/photos/16-min.jpg'], 'May 6, 2020');
INSERT INTO blogEntries (title, slug, article, coverUrl, photoUrls, dateString) 
VALUES ('Post Title 3', 'post-title-3', 'Ethical cloud bread celiac, succulents actually bitters etsy mumblecore chia vinyl raw denim kogi forage. Franzen scenester mustache church-key synth. Unicorn everyday carry seitan cloud bread. Pok pok succulents humblebrag mixtape knausgaard. Tilde bitters everyday carry pug echo park fixie umami vexillologist squid bicycle rights biodiesel.'||chr(10)||'Im baby photo booth heirloom thundercats kitsch organic direct trade af ethical franzen health goth man braid dreamcatcher tumblr vape. Authentic messenger bag XOXO, pabst iPhone disrupt gochujang occupy venmo crucifix narwhal keytar edison bulb. Subway tile tumblr shaman, tattooed hot chicken tilde 90s gochujang fam gluten-free. Hammock succulents pour-over chillwave meggings chia.'||chr(10)||'Im baby photo booth heirloom thundercats kitsch organic direct trade af ethical franzen health goth man braid dreamcatcher tumblr vape. Authentic messenger bag XOXO, pabst iPhone disrupt gochujang occupy venmo crucifix narwhal keytar edison bulb. Subway tile tumblr shaman, tattooed hot chicken tilde 90s gochujang fam gluten-free. Hammock succulents pour-over chillwave meggings chia.', 
'/paintings/pawel-czerwinski-snrPBiLzZaE-unsplash-min.jpg',  ARRAY['/paintings/sergio-souza-gOzD9CZTwXw-unsplash-min.jpg', '/paintings/tamara-menzi-n-vnWQmmVoY-unsplash-min.jpg', '/photos/5-min.jpg', '/photos/7-min.jpg'], 'June 6, 2020');
INSERT INTO blogEntries (title, slug, article, coverUrl, photoUrls, dateString) 
VALUES ('Post Title 4', 'post-title-4', 'Ethical cloud bread celiac, succulents actually bitters etsy mumblecore chia vinyl raw denim kogi forage. Franzen scenester mustache church-key synth. Unicorn everyday carry seitan cloud bread. Pok pok succulents humblebrag mixtape knausgaard. Tilde bitters everyday carry pug echo park fixie umami vexillologist squid bicycle rights biodiesel.'||chr(10)||'Im baby photo booth heirloom thundercats kitsch organic direct trade af ethical franzen health goth man braid dreamcatcher tumblr vape. Authentic messenger bag XOXO, pabst iPhone disrupt gochujang occupy venmo crucifix narwhal keytar edison bulb. Subway tile tumblr shaman, tattooed hot chicken tilde 90s gochujang fam gluten-free. Hammock succulents pour-over chillwave meggings chia.'||chr(10)||'Im baby photo booth heirloom thundercats kitsch organic direct trade af ethical franzen health goth man braid dreamcatcher tumblr vape. Authentic messenger bag XOXO, pabst iPhone disrupt gochujang occupy venmo crucifix narwhal keytar edison bulb. Subway tile tumblr shaman, tattooed hot chicken tilde 90s gochujang fam gluten-free. Hammock succulents pour-over chillwave meggings chia.', 
'/photos/16-min.jpg',  ARRAY['/paintings/steve-johnson-VCLNNMRl07k-unsplash-min.jpg', '/paintings/falco-negenman-kdNs6NZMaD4-unsplash-min.jpg', '/photos/11-min.jpg', '/photos/15-min.jpg'], 'April 8, 2020');
INSERT INTO blogEntries (title, slug, article, coverUrl, photoUrls, dateString) 
VALUES ('Post Title 5', 'post-title-5', 'Ethical cloud bread celiac, succulents actually bitters etsy mumblecore chia vinyl raw denim kogi forage. Franzen scenester mustache church-key synth. Unicorn everyday carry seitan cloud bread. Pok pok succulents humblebrag mixtape knausgaard. Tilde bitters everyday carry pug echo park fixie umami vexillologist squid bicycle rights biodiesel.'||chr(10)||'Im baby photo booth heirloom thundercats kitsch organic direct trade af ethical franzen health goth man braid dreamcatcher tumblr vape. Authentic messenger bag XOXO, pabst iPhone disrupt gochujang occupy venmo crucifix narwhal keytar edison bulb. Subway tile tumblr shaman, tattooed hot chicken tilde 90s gochujang fam gluten-free. Hammock succulents pour-over chillwave meggings chia.'||chr(10)||'Im baby photo booth heirloom thundercats kitsch organic direct trade af ethical franzen health goth man braid dreamcatcher tumblr vape. Authentic messenger bag XOXO, pabst iPhone disrupt gochujang occupy venmo crucifix narwhal keytar edison bulb. Subway tile tumblr shaman, tattooed hot chicken tilde 90s gochujang fam gluten-free. Hammock succulents pour-over chillwave meggings chia.', 
'/photos/19-min.jpg',  ARRAY['/paintings/pawel-czerwinski-snrPBiLzZaE-unsplash-min.jpg', '/paintings/bruce-warrington-oGSCKjhcJ9o-unsplash-min.jpg', '/photos/14-min.jpg', '/photos/6-min.jpg'], 'April 6, 2020');
